name: Deploy Website

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install OpenAPI Generator CLI
        run: |
          npm install -g @openapitools/openapi-generator-cli@2.13.4

      - name: Generate API Documentation
        run: |
          cd tools/gendocs
          go run main.go param.go
          cd ../..
          make restful-api-doc
          openapi-generator-cli generate -i .docs/swagger.yaml -g markdown -o ./docs-generated --template-dir ./markdown-template --skip-validate-spec
          cp docs-generated/README.md docs/api-documentation.md
          cp -r docs-generated/Apis docs/

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Prepare docs with front-matter
        run: |
          ./scripts/website-preprocess.sh

      - name: Build and deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          # ── build inside docs ───────────────────
          cd docs
          bundle install --quiet
          bundle exec jekyll build
          # ── deploy from repo root ───────────────
          cd "$GITHUB_WORKSPACE"
          npm install -g netlify-cli
          netlify deploy --dir=docs/_site --prod
